language: node_js
node_js:
  - "node"
notifications:
  email: false
install:
  - npm install -g yarn
  - yarn
  - cd nin/frontend && yarn && cd -
script:
  - cd nin/backend && ../../node_modules/.bin/eslint .
  - cd ../frontend && make lint
